name: recipe_meal_planner
description: A Flutter recipe and meal planning app with SQLite and sharing features.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path: ^1.9.0
  share_plus: ^12.0.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - C:\inclass4\recipe_planner_app\assets\images\burger.jpg
    - C:\inclass4\recipe_planner_app\assets\images\burrito.jpg
    - C:\inclass4\recipe_planner_app\assets\images\chicken_curry.jpg
    - C:\inclass4\recipe_planner_app\assets\images\fried_rice.jpg
    - C:\inclass4\recipe_planner_app\assets\images\fruit_salad.jpg
    - C:\inclass4\recipe_planner_app\assets\images\grilled_fish.jpg
    - C:\inclass4\recipe_planner_app\assets\images\noodles.jpg
    - C:\inclass4\recipe_planner_app\assets\images\omelette.jpg
    - C:\inclass4\recipe_planner_app\assets\images\pancakes.jpg
    - C:\inclass4\recipe_planner_app\assets\images\pizza.jpg
    - C:\inclass4\recipe_planner_app\assets\images\salad.jpg
    - C:\inclass4\recipe_planner_app\assets\images\sandwich.jpg
    - C:\inclass4\recipe_planner_app\assets\images\smoothie.jpg
    - C:\inclass4\recipe_planner_app\assets\images\tomato_soup.jpg
    - C:\inclass4\recipe_planner_app\assets\images\veggie_pasta.jpg
