name: recipe_meal_planner
description: A Flutter recipe and meal planning app with SQLite and sharing features.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path: ^1.9.0
  share_plus: ^12.0.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/burger.jpg
    - assets/images/burrito.jpg
    - assets/images/chicken_curry.jpg
    - assets/images/fried_rice.jpg
    - assets/images/fruit_salad.jpg
    - assets/images/grilled_fish.jpg
    - assets/images/noodles.jpg
    - assets/images/omelette.jpg
    - assets/images/pancakes.jpg
    - assets/images/pizza.jpg
    - assets/images/salad.jpg
    - assets/images/sandwich.jpg
    - assets/images/smoothie.jpg
    - assets/images/tomato_soup.jpg
    - assets/images/veggie_pasta.jpg
